### ISSUE TITLE
Writing a Time field and Accounting for DST

### ISSUE THREAD

**Issue by gitmijn** [clemens/delocalize#60]
The delocalize is a great gem. I am surprised its functionality is not a default part of rails.

I have encountered an issue when writing a time to my postgres database and the time_zone. I have form where a user can input their opening/starting and closing/ending time for each day of a seven day week. When the user submits the form and stores the time in a time form in the database.

Here's the params passed by the edit view (US Eastern time zone set)

``` ruby
... "sched_mon_start"=>" 8:30 AM", ...
```

And heres the log of rails inserts into the database.

``` sql
... SET "sched_mon_start" = '2013-04-25 12:30:00.000000', ...
```

And this is how the time is stored in the database like so

> sched_mon_start: 2000-01-01 12:30:00 UTC

The problem is today (April 25), the East coast is UTC -4 but in January it is UTC -5. So the view shows up as an hour earlier. Also, when a user cycles between edit/save/show/edit/save/show the times crawl back one hour each commit.

**Is there a fix for this that I am overlooking? Can I turn off the delocalize gem for these inputs?**

I am using this with simple_form and here's my en.yml:

``` yaml
 time:
    input:
      formats: 
        - :default
        - :long
        - :short
        - :time
        - :date
    formats:
      default: "%m/%d/%Y %I:%M%p"
      short: "%B %e %I:%M %p"
      long: "%A, %B %e, %Y %I:%M%p"
      time: "%l:%M%p"
      date: "%m/%d/%Y"
    pm: PM
    am: AM
```
