### ISSUE TITLE
Delocalize in Production

### ISSUE THREAD

**Issue by gitmijn** [clemens/delocalize#61]
Delocalize continues to work well for me in production.

I am using Delocalize on a date column with my yaml configured like so:

``` yaml
  date:
    input:
      formats:
        - :default
        - :long
        - :short
    formats:
      default: ! '%d/%m/%Y'
      long:    ! '%B %d, %Y'
      short:   ! '%b %d'
    placeholder:
      default: 'dd/mm/yyyy'
```

I am using simple_form and I am initializing the input like so:

``` ruby
      <%= f.input :birth_date, 
          as:'string', 
          label:"DOB", 
          input_html: {include_blank:true, 
            value: date_format(f.object.birth_date), 
            class: "datepicker",
            placeholder: ( t 'date.placeholder.default' )} %>
```
